### PR TITLE
Make popup

### PR DESCRIPTION
**Pull request by anyaguuu**
# Description

Please include a summary of the feature/fix. Please also include relevant motivation and context.

## Type of change

Please delete options that are not relevant.

- [ ] clicking on pencil icon on profile page brings up an edit profile popup

# How Has This Been Tested?

Please include:
- Instructions to reproduce the intended result
- How you tested it and what cases you tested with, including edge cases
- Any other relevant info regarding this feature/fix

### CODE REVIEW

**Comment by willie-yao** [comment]
Can you make the dialog window slightly wider on larger screens like the surface duo or ipad? Other than that it looks good!

image

**Comment by henryyqin** [comment]
Seconding Willie; it would be great if it could be wider on all screens!

**Comment by anyaguuu** [comment]
Okay will do!

**Comment by willie-yao** [comment]
Getting this error when running. I think you accidentally deleted ProfileDialogStyles
image

**Comment by willie-yao** [comment]
LGTM

**Review by willie-yao — APPROVED** [review]

**Pull request merged**
