### PR TITLE
Ride notes

### PR DESCRIPTION
**Pull request by shreyasminocha**
# Description

Allows users to add some notes when creating rides. Displays those notes on the ride summary page.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please include:
- Try creating a new ride
- Fill out the optional notes field
- Confirm that the ride summary page includes those notes
- Confirm that it's possible to create a ride without filling out the notes field

### CODE REVIEW

**Comment by willie-yao** [comment]
@shreyasminocha minor thing: can you make the notes field the same width as the rest of the elements on the create ride page?

**Comment by willie-yao** [comment]
@shreyasminocha I would also move the notes field under the user list, and add a bit of styling. I think the font might be off and adding a different colored box would help it pop out more

**Comment by shreyasminocha** [comment]
White notes box under the list of riders

**Comment by willie-yao** [comment]
Nice, LGTM

**Review by willie-yao — APPROVED** [review]

**Pull request merged**
