### PR TITLE
About us page

### PR DESCRIPTION
**Pull request by kim-audrey**
# Description

Finished up the about us page! has FAQ and meet the team and feedback

## Type of change

Please delete options that are not relevant.

- [ ] New page!

# How Has This Been Tested?
- It looks fine on all mobile views
- The feedback form links to the right form!

### CODE REVIEW

**Comment by willie-yao** [comment]
Looks amazing! Can you remove the warnings from the console? @kim-audrey

**Comment by alexisnic01as** [comment]
removed those warnings! however, I did see that the navbar icons turned white when we are in the aboutus page;; i'll have to double check

**Comment by willie-yao** [comment]
Mobile versions of the about page now look a bit too wide @alexisnic01as 
image

**Comment by alexisnic01as** [comment]
I was unable to reproduce how it was too wide;; but I did make some slight changes

**Review by willie-yao — APPROVED** [review]
It looks good now, thanks!

**Pull request merged**
