### PR TITLE
New Landing Page

### PR DESCRIPTION
**Pull request by KataTech**
# Description

Implemented the new landing page. A PNG file of the logo is uploaded into the public folder. 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

It looks good on the common screen options available. I made the text above the button into two separate divs to ensure that they are always displayed like that, but this causes issues if the screen is really thin (aka. Galaxy Fold)

Screen Shot 2022-02-26 at 3 36 40 PM

### CODE REVIEW

**Review by willie-yao — CHANGES_REQUESTED** [review]
White borders on certain phone sizes

**Comment by henryyqin** [comment]
Could you also lower the title and logo closer to the center? (Screenshot on XR for reference)
Screen Shot 2022-02-27 at 12 27 40 AM

**Comment by KataTech** [comment]
Iphone XR 

Screen Shot 2022-02-27 at 3 36 53 PM

**Comment by KataTech** [comment]
Accidentally closed the PR.

**Review by willie-yao — APPROVED** [review]
LGTM

**Pull request merged**
