### PR TITLE
Puts @ in front of venmo text

### PR DESCRIPTION
**Pull request by kim-audrey**
# Description

Puts the @ symbol in the venmo field on onboarding form. 

## Type of change

CSS Change

# How Has This Been Tested?

This has been tested by going onto the onboarding form and seeing that the @ is there as well as making sure that when a new user onboards their data is sent properly and without the @.

### CODE REVIEW

**Review by henryyqin — CHANGES_REQUESTED** [review]
Can you also do this for the edit profile popup? Thanks!

**Comment by kim-audrey** [comment]
Added the @ symbol to the profile dialogue page!

**Review by henryyqin — APPROVED** [review]

**Review by henryyqin — CHANGES_REQUESTED** [review]
Requesting to resolve merge conflicts (ProfileForm no longer exists in current version of master)

**Comment by kim-audrey** [comment]
Done!

**Review by henryyqin — APPROVED** [review]

**Pull request merged**
