### PR TITLE
Onboarding

### PR DESCRIPTION
**Pull request by shreyasminocha**
# Description

When a new user signs in through SSO we present them with an onboarding form that asks for their name, contact info, payment info etc. When they submit the form, a DB record is created and they get redirected to the page they signed in from or the search rides page, depending on how they got to the onboarding prompt.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

They sign in with a netid that isn't associated with a user in the DB (aka they're a new user). They must be taken to the onboarding page (`/onboarding`). When they submit the form, their info must show up as a new document in the DB. Upon submitting the form, they must be redirected to a page. If they signed in from a ride summary page or the create ride page, they must be taken to that page. Else they must be taken to the ride search page.

/ping @KataTech

### CODE REVIEW

**Comment by willie-yao** [comment]
I deleted my user from MongoDB but I was not redirected to the onboarding form. I used the login button from the navbar. Is this an issue you guys have?

**Review by henryyqin — COMMENTED** [review]
Testing this by removing myself as a user from the DB and clearing my browsing data. Same as Willie, I'm don't get routed to onboarding after logging in from the navbar. When I test it from the create ride button, I do get routed to onboarding, and after filling it out, a new user is made and rerouted to /create-ride (nice). But then I get a TypeError: locationData undefined and the page is blank. Do you guys get these on your end?

Also, it would be really helpful if you could sort out the merge conflicts by pulling from master!

**Comment by KataTech** [comment]
The CreateRide page errors when it is directly routed from UserAuth via `useHistory`'s `history.go` function, so I fixed that with the build-in `window.open` function instead. This may not be the best fix since it's less consistent with other portions of the code that uses `useHistory` or `Redirect` components, but for now- this fixes the issue. 

As for login button not directing to onboarding page, I forgot to account for the login button as a source for triggering the onboarding form. So I modified the auth page such that if it is routed from a different page without a specified "nextPage" within localStorage, then it must have came from the login button and the logical next destination would be going back to home page. If we want it to route elsewhere by default, let me know!

**Review by willie-yao — APPROVED** [review]
Looks good now! One thing is that if I sign in through creating a new ride, my details don't get added to the backend once filling out the onboarding form. We can address this in a later PR. Good work!

**Pull request merged**
