### PR TITLE
updated ride summary css

### PR DESCRIPTION
**Pull request by alexisnic01as**
# Description

Added back shadows to each user!
when hovering (on desktop) cursor turns to a pointer.
Also changed color of leave ride button to match design.
changed the div to 100% so it's not scrollable.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

image

### CODE REVIEW

**Comment by alexisnic01as** [comment]
should we change the nav bar color? i think this also applies to user profile page as well

**Comment by alexisnic01as** [comment]
also, i think i should be able to fix the scrollable issue, and keep the background color uniform

**Comment by willie-yao** [comment]
> should we change the nav bar color? i think this also applies to user profile page as well

Yes we would prefer if the navbar would match

**Comment by willie-yao** [comment]
There's also a white bar at the bottom 
image

**Comment by alexisnic01as** [comment]
alright, I'll make a separate pr for that!

**Comment by alexisnic01as** [comment]
oh oops, i didn't realize I already made the pr on #162 !

**Review by willie-yao — APPROVED** [review]
LGTM!

**Pull request merged**
