### PR TITLE
Fix routing back from onboarding

### PR DESCRIPTION
**Pull request by KataTech**
# Description

Bug fix for routing issue. Previously, I have set up the onboarding route as: userAuth -> (if user's information doesn't exist in our MongoDB) onboardingPrompt, (else) their intended page.  However, there is no account for any unexpected flow such as when the user presses the back button. So, I have included a check for the user attempting to navigate away via a back button, utilize new localStorage variable "from" to indicate the page that the user attempts to come back from. 

Now, the behavior is that there will be a warning if the user attempts to navigate away from onboarding form that it will be unsafe, and that navigating back to onboarding form from createRide will also not be recommended. 

## Type of change

Please delete options that are not relevant.

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

The feature is tested by attempting to go back upon reaching the onboarding page (for a user that doesn't have information already within our database, in that case- the pop-up should show up to warn the user. Same for if the user attempts to go back from createRide after just filling out the onboarding form. That will also result in a warning pop-up. 

For a user that is already completed onboarding, if they just navigated from Rice login then it will result in the Rice "you just came back and for security reasons nothing useful is displayed" page - but they can hit back again and just get to search, and if they already logged in, back from createRide will take them back to search. 

A potential issue I notice is that if there's an attempt to go back very fast upon landing a page, the pop-up sometimes doesn't show up. It was a little weird and I wasn't sure if something was wrong with the code or it just takes a while for the useEffect to fully settle into effect. I feel like most users probably won't actively try to break the code like this though.

### CODE REVIEW

**Comment by willie-yao** [comment]
I tested this by deleting my user from the database. I got to the onboarding page but when I hit back, I didn't get any sort of warning, and went back to the Rice SSO page. Does this work for you? @KataTech

**Comment by willie-yao** [comment]
This is what is printed in the console for me
image

**Comment by KataTech** [comment]
Updates from 01/22: 

Identified the inconsistency in pop-up on back button as an innate security measure of Google Chrome to protect the user. Long story short, Chrome does not allow websites to detect user's back button unless the user has interacted with the page in some form already. Therefore, back button usage cannot be detected if the user goes back immediately upon arriving on the onboarding page. Alternative proposed: use a toast to alert the user about the consequences and prompt them to use a cancel button instead. 

Changes: 
- Included toast for alerting the user about the consequences of going back & prompt them to use cancel button instead
- Included cancel button in onboarding form that wipes the user from the database and takes them to the previously recognized page, home (search) page by default if the previous page is somehow not stored

**Comment by zawie** [comment]
Nice

**Comment by willie-yao** [comment]
@KataTech Can you fix the merge conflicts? Also, after successfully onboarding and joining a ride, my name doesn't show up on the right list, and hitting the back button on the page (not the browser back button) brings me to an empty page

**Comment by KataTech** [comment]
Updated the code again. Previously there was a breaking error because some of the string retrieved from "lastPage" in the localStorage already contained the "/" character. When using the back button in ride summary, that "/" character is appended once again to the front of the address. I deleted the "/" character from all of the strings that is stored into the localStorage that I can find. I tried to jump around different pages, and attempting to onboard from different pages, and couldn't run into anymore errors.

**Review by henryyqin — APPROVED** [review]

**Pull request merged**
