### PR TITLE
Add join/leave email notifications

### PR DESCRIPTION
**Pull request by shreyasminocha**
# Description

Notify the ride owner when someone leaves or joins their ride.

Note: the signature image in the html version of the email won't currently show up because it depends on this PR being merged into production.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

You'll have to add `SENDER_EMAIL=ricecarpool@gmail.com` and `SENDER_EMAIL_PASSWORD` to the `api/` `.env`. You can get the password from Shreya.

- Join someone's ride (or have them join yours)
- Check the owner's inbox for an email
- Make sure it doesn't say or link to anything wacky

Spec from Shreya:

```
subject: Rice Carpool: Shreyas left your ride
text:
Shreyas Minocha left your ride from (Rice) to (IAH) on (May 6, 2022).
See (link) for details.
[rice carpool email signature]
```

### CODE REVIEW

**Review by willie-yao — CHANGES_REQUESTED** [review]
Something is broken with the signature image for me
image

**Comment by willie-yao** [comment]
I also don't get email notifs for people leaving my ride, unless it's me who leaves and joins my own ride for whatever reason

**Comment by shreyasminocha** [comment]
> Something is broken with the signature image for me

Oh yeah that's 'cause it depends on this PR being merged into production because I link to `https://carpool.riceapps.org/logo-with-wordmark.png`.

> I also don't get email notifs for people leaving my ride, unless it's me who leaves and joins my own ride for whatever reason

That's odd. For what it's worth I just received these emails:

William joined your ride; William left your ride

**Comment by willie-yao** [comment]
> Oh yeah that's 'cause it depends on this PR being merged into production because I link to `https://carpool.riceapps.org/logo-with-wordmark.png`.

I see! That shouldn't be a problem then.

> That's odd. For what it's worth I just received these emails:
> 
> William joined your ride; William left your ride

Hmm okay I'll try and test it again. Maybe the rides I created were broken? Or do both people have to be on this branch to receive email notifs?

**Review by willie-yao — APPROVED** [review]
LGTM

**Pull request merged**
